### PR TITLE
Mainly Improving the following:

### PR DESCRIPTION
**Pull request by DeppWang**
1. regex; 2. filter graph bad URL; 3. download and update image; 4. Format a part of code

### CODE REVIEW

**Comment by crossoverJie** [comment]
Please split it into several pr by type.

It is not easy to review like this.

**Comment by DeppWang** [comment]
> Please split it into several pr by type.
> 
> It is not easy to review like this.

OK

**Comment by DeppWang** [comment]
I just can according the commit sequence to split it, please review the request in order.

**Comment by DeppWang** [comment]
All pull requsts have been initiated.

**Pull request closed without merging**
